<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>58ac3ef4-867c-4231-91ed-fae5c8c5b87f</UserSecretsId>
  </PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.0" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
		<PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="6.0.1" />
	</ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Movie_Watchlist.Application\Movie_Watchlist.Application.csproj" />
	
  </ItemGroup>

</Project>
